import Link from 'next/link';
import { cookies } from 'next/headers';

const API_BASE_URL = process.env.INTERNAL_API_URL || 'http://backend:4000';

async function checkAuthServer() {
  try {
    const cookieStore = await cookies();
    const cookieHeader = cookieStore.getAll().map(c => `${c.name}=${c.value}`).join('; ');
    const response = await fetch(`${API_BASE_URL}/auth/me`, {
      method: 'GET',
      headers: { Cookie: cookieHeader },
      cache: 'no-store',
    });
    if (response.ok) {
      const data = await response.json();
      return { isAuthenticated: true, user: data.user };
    }
  } catch {}
  return { isAuthenticated: false, user: null };
}

export default async function Home() {
  const { isAuthenticated, user } = await checkAuthServer();

  return (
    <div className="max-w-6xl mx-auto">
      {/* Hero Section */}
      <div className="text-center py-12 px-4">
        <h1 className="text-5xl font-bold text-gray-900 mb-6">
          Afeka Trip Planner 2026
        </h1>
        <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
          Plan your perfect hiking or cycling adventure with AI-generated routes, 
          real-time weather forecasts, and interactive maps.
        </p>
        
        {isAuthenticated ? (
          <div className="bg-green-50 border border-green-200 rounded-lg p-6 mb-8">
            <h2 className="text-2xl font-semibold text-green-800 mb-2">
              Welcome back, {user?.firstName || user?.email}!
            </h2>
            <p className="text-green-700 mb-4">
              Ready to plan your next adventure or review your trip history?
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href="/planning"
                className="px-6 py-3 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 transition-colors"
              >
                Start Planning
              </Link>
              <Link
                href="/history"
                className="px-6 py-3 bg-gray-800 text-white font-medium rounded-lg hover:bg-gray-900 transition-colors"
              >
                View History
              </Link>
            </div>
          </div>
        ) : (
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 mb-8">
            <h2 className="text-2xl font-semibold text-blue-800 mb-2">
              Get Started Today
            </h2>
            <p className="text-blue-700 mb-4">
              Create an account to start planning your trips and save them for later.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href="/register"
                className="px-6 py-3 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 transition-colors"
              >
                Sign Up Free
              </Link>
              <Link
                href="/login"
                className="px-6 py-3 bg-white text-blue-600 border border-blue-600 font-medium rounded-lg hover:bg-blue-50 transition-colors"
              >
                Login
              </Link>
            </div>
          </div>
        )}
      </div>

      {/* Features Section */}
      <div className="grid md:grid-cols-3 gap-8 py-12">
        <div className="bg-white p-6 rounded-xl shadow-lg border border-gray-200">
          <div className="text-blue-600 text-3xl mb-4">🗺️</div>
          <h3 className="text-xl font-semibold text-gray-900 mb-3">
            AI-Generated Routes
          </h3>
          <p className="text-gray-600">
            Get realistic hiking (5-10km circular) or cycling (30-70km city-to-city) 
            routes generated by advanced LLM models.
          </p>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-lg border border-gray-200">
          <div className="text-blue-600 text-3xl mb-4">⛅</div>
          <h3 className="text-xl font-semibold text-gray-900 mb-3">
            3-Day Weather Forecast
          </h3>
          <p className="text-gray-600">
            Every route includes a detailed 3-day weather forecast to help you 
            plan the perfect timing for your adventure.
          </p>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-lg border border-gray-200">
          <div className="text-blue-600 text-3xl mb-4">💾</div>
          <h3 className="text-xl font-semibold text-gray-900 mb-3">
            Save & Review Trips
          </h3>
          <p className="text-gray-600">
            Save your favorite routes to your personal history and get updated 
            weather forecasts for future dates.
          </p>
        </div>
      </div>

      {/* How It Works */}
      <div className="bg-gray-100 rounded-2xl p-8 my-12">
        <h2 className="text-3xl font-bold text-gray-900 mb-8 text-center">
          How It Works
        </h2>
        <div className="grid md:grid-cols-4 gap-6">
          <div className="text-center">
            <div className="w-12 h-12 bg-blue-600 text-white rounded-full flex items-center justify-center text-xl font-bold mx-auto mb-4">
              1
            </div>
            <h4 className="font-semibold text-gray-900 mb-2">Sign Up</h4>
            <p className="text-gray-600 text-sm">
              Create your free account
            </p>
          </div>
          <div className="text-center">
            <div className="w-12 h-12 bg-blue-600 text-white rounded-full flex items-center justify-center text-xl font-bold mx-auto mb-4">
              2
            </div>
            <h4 className="font-semibold text-gray-900 mb-2">Plan Trip</h4>
            <p className="text-gray-600 text-sm">
              Choose hiking or cycling and location
            </p>
          </div>
          <div className="text-center">
            <div className="w-12 h-12 bg-blue-600 text-white rounded-full flex items-center justify-center text-xl font-bold mx-auto mb-4">
              3
            </div>
            <h4 className="font-semibold text-gray-900 mb-2">Generate Route</h4>
            <p className="text-gray-600 text-sm">
              Get AI-generated route with weather
            </p>
          </div>
          <div className="text-center">
            <div className="w-12 h-12 bg-blue-600 text-white rounded-full flex items-center justify-center text-xl font-bold mx-auto mb-4">
              4
            </div>
            <h4 className="font-semibold text-gray-900 mb-2">Save & Go</h4>
            <p className="text-gray-600 text-sm">
              Save trip and view in history
            </p>
          </div>
        </div>
      </div>

      {/* Call to Action */}
      <div className="text-center py-12">
        <h2 className="text-3xl font-bold text-gray-900 mb-4">
          Ready to Start Your Adventure?
        </h2>
        <p className="text-gray-600 mb-8 max-w-2xl mx-auto">
          Join thousands of students and outdoor enthusiasts who use Afeka Trip Planner 
          to discover amazing routes and plan perfect trips.
        </p>
        <Link
          href={isAuthenticated ? "/planning" : "/register"}
          className="inline-block px-8 py-4 bg-gradient-to-r from-blue-600 to-purple-600 text-white font-semibold rounded-lg hover:from-blue-700 hover:to-purple-700 transition-all transform hover:scale-105"
        >
          {isAuthenticated ? "Plan Your Next Trip" : "Get Started Free"}
        </Link>
      </div>
    </div>
  );
}
